# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ronin-team}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dustin Willis Webber", "Postmodern"]
  s.date = %q{2010-09-13}
  s.default_executable = %q{ronin-team}
  s.description = %q{Ronin Team is a real-time web application, designed to help Security Researchers collaborate.}
  s.email = %q{ronin-ruby@googlegroups.com}
  s.executables = ["ronin-team"]
  s.extra_rdoc_files = [
    "ChangeLog.md",
    "README.md"
  ]
  s.files = [
    ".gitignore",
    ".rspec",
    ".yardopts",
    "COPYING.txt",
    "ChangeLog.md",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "bin/ronin-team",
    "config.ru",
    "data/ronin/team/public/css/console.css",
    "data/ronin/team/public/css/images/ui-bg_diagonals-thick_18_b81900_40x40.png",
    "data/ronin/team/public/css/images/ui-bg_diagonals-thick_20_666666_40x40.png",
    "data/ronin/team/public/css/images/ui-bg_flat_10_000000_40x100.png",
    "data/ronin/team/public/css/images/ui-bg_glass_100_f6f6f6_1x400.png",
    "data/ronin/team/public/css/images/ui-bg_glass_100_fdf5ce_1x400.png",
    "data/ronin/team/public/css/images/ui-bg_glass_65_ffffff_1x400.png",
    "data/ronin/team/public/css/images/ui-bg_gloss-wave_35_f6a828_500x100.png",
    "data/ronin/team/public/css/images/ui-bg_highlight-soft_100_eeeeee_1x100.png",
    "data/ronin/team/public/css/images/ui-bg_highlight-soft_75_ffe45c_1x100.png",
    "data/ronin/team/public/css/images/ui-icons_222222_256x240.png",
    "data/ronin/team/public/css/images/ui-icons_228ef1_256x240.png",
    "data/ronin/team/public/css/images/ui-icons_ef8c08_256x240.png",
    "data/ronin/team/public/css/images/ui-icons_ffd27a_256x240.png",
    "data/ronin/team/public/css/images/ui-icons_ffffff_256x240.png",
    "data/ronin/team/public/css/jquery-ui.css",
    "data/ronin/team/public/css/roninteam.css",
    "data/ronin/team/public/images/break.png",
    "data/ronin/team/public/images/clouds.png",
    "data/ronin/team/public/images/diamond.png",
    "data/ronin/team/public/images/header-bg.png",
    "data/ronin/team/public/images/icons/link.png",
    "data/ronin/team/public/images/icons/mail.png",
    "data/ronin/team/public/images/logo-intro.png",
    "data/ronin/team/public/images/logo-water.png",
    "data/ronin/team/public/images/logo.png",
    "data/ronin/team/public/images/tipsy.gif",
    "data/ronin/team/public/images/user-list.png",
    "data/ronin/team/public/images/user.png",
    "data/ronin/team/public/js/Datejs.js",
    "data/ronin/team/public/js/console.js",
    "data/ronin/team/public/js/faye.js",
    "data/ronin/team/public/js/growl.js",
    "data/ronin/team/public/js/jquery-ui.js",
    "data/ronin/team/public/js/jquery.js",
    "data/ronin/team/public/js/jquery.livequery.js",
    "data/ronin/team/public/js/jquery.tipsy.js",
    "data/ronin/team/public/js/raphael.js",
    "data/ronin/team/public/js/roninteam.js",
    "data/ronin/team/public/js/scrollto.js",
    "data/ronin/team/views/chat.erb",
    "data/ronin/team/views/console.erb",
    "data/ronin/team/views/docs_not_found.erb",
    "data/ronin/team/views/intro.erb",
    "data/ronin/team/views/layout.erb",
    "data/ronin/team/views/login.erb",
    "data/ronin/team/views/notifications.erb",
    "lib/ronin/database/migrations/team.rb",
    "lib/ronin/database/migrations/team/create_users_table.rb",
    "lib/ronin/team.rb",
    "lib/ronin/team/user.rb",
    "lib/ronin/team/version.rb",
    "lib/ronin/ui/command_line/commands/team.rb",
    "lib/ronin/ui/web/team.rb",
    "lib/ronin/ui/web/team/app.rb",
    "lib/ronin/ui/web/team/helpers.rb",
    "lib/ronin/ui/web/team/warden.rb",
    "ronin-team.gemspec"
  ]
  s.has_rdoc = %q{yard}
  s.homepage = %q{http://github.com/mephux/ronin-team}
  s.licenses = ["GPL-2"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Real-Time Security Research}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bcrypt-ruby>, ["~> 2.1.0"])
      s.add_runtime_dependency(%q<dm-serializer>, ["~> 1.0.2"])
      s.add_runtime_dependency(%q<dm-is-authenticatable>, ["~> 0.1.0"])
      s.add_runtime_dependency(%q<faye>, ["~> 0.5.0"])
      s.add_runtime_dependency(%q<uuidtools>, ["~> 2.1.1"])
      s.add_runtime_dependency(%q<sinatra>, ["~> 1.0"])
      s.add_runtime_dependency(%q<sinatra_warden>, ["~> 0.3.0"])
      s.add_runtime_dependency(%q<ronin-support>, ["~> 0.1.0"])
      s.add_runtime_dependency(%q<ronin>, ["~> 0.4.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<rake>, ["~> 0.8.7"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.0.pre"])
      s.add_development_dependency(%q<rspec>, ["~> 2.0.0.beta.20"])
    else
      s.add_dependency(%q<bcrypt-ruby>, ["~> 2.1.0"])
      s.add_dependency(%q<dm-serializer>, ["~> 1.0.2"])
      s.add_dependency(%q<dm-is-authenticatable>, ["~> 0.1.0"])
      s.add_dependency(%q<faye>, ["~> 0.5.0"])
      s.add_dependency(%q<uuidtools>, ["~> 2.1.1"])
      s.add_dependency(%q<sinatra>, ["~> 1.0"])
      s.add_dependency(%q<sinatra_warden>, ["~> 0.3.0"])
      s.add_dependency(%q<ronin-support>, ["~> 0.1.0"])
      s.add_dependency(%q<ronin>, ["~> 0.4.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<rake>, ["~> 0.8.7"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.0.pre"])
      s.add_dependency(%q<rspec>, ["~> 2.0.0.beta.20"])
    end
  else
    s.add_dependency(%q<bcrypt-ruby>, ["~> 2.1.0"])
    s.add_dependency(%q<dm-serializer>, ["~> 1.0.2"])
    s.add_dependency(%q<dm-is-authenticatable>, ["~> 0.1.0"])
    s.add_dependency(%q<faye>, ["~> 0.5.0"])
    s.add_dependency(%q<uuidtools>, ["~> 2.1.1"])
    s.add_dependency(%q<sinatra>, ["~> 1.0"])
    s.add_dependency(%q<sinatra_warden>, ["~> 0.3.0"])
    s.add_dependency(%q<ronin-support>, ["~> 0.1.0"])
    s.add_dependency(%q<ronin>, ["~> 0.4.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<rake>, ["~> 0.8.7"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.0.pre"])
    s.add_dependency(%q<rspec>, ["~> 2.0.0.beta.20"])
  end
end

